
server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Support Angular HTML5 fallback routing
    location / {
        try_files $uri $uri/ /index.html;
    }


    # Error page fallback
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
